In [42]:
#!pip3 install pandas

In [85]:
import pandas as pd

# Reading data from csv file into a data frame without specifying header
df = pd.read_csv("salaries.csv", header=None)

# Setting 1st row as header (column names of df)
df.columns = df.iloc[0]

# keys = df.iloc[0].tolist()
# py_dict = {key: None for key in keys}

# print(py_dict)

# Dropping 1st row since we are using it as header
df = df[1:].reset_index(drop=True)

# Setting PlayerID column as index column
df.set_index('playerID', inplace=True)

# converting salary to int
df['salary'] = df['salary'].astype(int)

# print("\nDataFrame after setting the first row as header:")
# print(df)
# print('-' * 40)

# Select ID of players: registerd in ATL or HOU && salary >= 1 million
filtered_ATL_OR_HOU_GREATER_THAN_MILLION_df = df[(df['teamID'].isin(['ATL', 'HOU'])) & (df['salary'] > 1000000)]

# print("\nDataFrame after filtering:")
# print(filtered_ATL_OR_HOU_GREATER_THAN_MILLION_df)
# print('-' * 40)

'''
Use describe to calculate:

a. standard deviation
b. first quartile
c. median
d. third quartile
e. mean
f. maximum
g. minimum 

of the salary in team ATL
'''

''' Manually calling funcs. to get each statistical value'''

# Filtering players with teamID as ATL
filtered_ATL_df = df[df['teamID'] == 'ATL']

# mean of salary
mean = filtered_ATL_df['salary'].mean()

# median of salary (odd data count: middle value, even data count: average of 2 middle values)
median = filtered_ATL_df['salary'].median()

# standard deviation (+ - of this value from mean, represents 68.26% of salary data)
std_dev = filtered_ATL_df['salary'].std()

# first quartile (salary below which 25% of the data exists)
first_quartile = filtered_ATL_df['salary'].quantile(0.25)

# third quartile (salary below which 75% of the data exists)
third_quartile = filtered_ATL_df['salary'].quantile(0.75)

maximum = filtered_ATL_df['salary'].max()
minimum = filtered_ATL_df['salary'].min()

print("mean", mean)
print("standard dev", std_dev)
print("median", median)
print("first quartile", first_quartile)
print("third quartile", third_quartile)
print("maximum", maximum)
print("minimum", minimum)

''' Using Describe to obtain same values '''
print('-'*40)
print(filtered_ATL_df['salary'].describe())

mean 2206239.316027088
standard dev 3432672.983237386
median 600000.0
first quartile 300000.0
third quartile 2390625.0
maximum 16061802
minimum 60000
----------------------------------------
count    8.860000e+02
mean     2.206239e+06
std      3.432673e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.390625e+06
max      1.606180e+07
Name: salary, dtype: float64


In [83]:
''' f.1) Converting df to dict using iterrows() '''

# Reading data from csv file into a data frame without specifying header
df = pd.read_csv("salaries.csv", header=None)

# Setting 1st row as header (column names of df)
df.columns = df.iloc[0]

keys = df.iloc[0].tolist()
py_dict = {key: [] for key in keys}

# Dropping 1st row since we are using it as header
df = df[1:].reset_index(drop=True)

for index, row in df.iterrows():
    py_dict['yearID'].append(row['yearID'])
    py_dict['teamID'].append(row['teamID'])
    py_dict['lgID'].append(row['lgID'])
    py_dict['playerID'].append(row['playerID'])
    py_dict['salary'].append(row['salary'])

print(py_dict)

{'yearID': ['1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '1985', '198

In [82]:
''' f.2) Converting df to dict using to_dict() '''

# Convert the DataFrame to a dictionary (default orientation)
df_dict = df.to_dict()

print("converted dict")
print(df_dict["salary"])

converted dict
{0: '870000', 1: '550000', 2: '545000', 3: '633333', 4: '625000', 5: '800000', 6: '150000', 7: '483333', 8: '772000', 9: '250000', 10: '1500000', 11: '455000', 12: '407500', 13: '275000', 14: '775000', 15: '1625000', 16: '616667', 17: '450000', 18: '120000', 19: '750000', 20: '1354167', 21: '800000', 22: '625000', 23: '480000', 24: '437500', 25: '512500', 26: '375000', 27: '641667', 28: '450000', 29: '483333', 30: '725000', 31: '1090000', 32: '560000', 33: '440000', 34: '547143', 35: '1472819', 36: '341667', 37: '128500', 38: '800000', 39: '558333', 40: '60000', 41: '130000', 42: '581250', 43: '121000', 44: '915000', 45: '272500', 46: '1000000', 47: '115000', 48: '177500', 49: '747500', 50: '580000', 51: '140000', 52: '160000', 53: '650000', 54: '800000', 55: '477500', 56: '130000', 57: '335000', 58: '300000', 59: '125000', 60: '370000', 61: '275000', 62: '260000', 63: '165000', 64: '240000', 65: '483333', 66: '779227', 67: '1075000', 68: '325000', 69: '365000', 70: '883

In [90]:
''' g) Converting dict to data frame & updating header of data frame '''
df_from_dict = pd.DataFrame(df_dict)
df_from_dict.columns = ['a', 'b', 'c', 'd', 'e']

print(df_from_dict)

          a    b   c          d         e
0      1985  ATL  NL  barkele01    870000
1      1985  ATL  NL  bedrost01    550000
2      1985  ATL  NL  benedbr01    545000
3      1985  ATL  NL   campri01    633333
4      1985  ATL  NL  ceronri01    625000
...     ...  ...  ..        ...       ...
25570  2015  WAS  NL  treinbl01    512800
25571  2015  WAS  NL  ugglada01    507500
25572  2015  WAS  NL  werthja01  21000000
25573  2015  WAS  NL  zimmejo02  16500000
25574  2015  WAS  NL  zimmery01  14000000

[25575 rows x 5 columns]


In [108]:
''' 5. Using Numpy'''

import numpy as np

# a) Create 2D python list & convert to np array
py_list = [[1,2,3],
           [4,5,6],
           [7,8,9],
           [10,11,12],
           ]

# Converting to np array
np_arr = np.array(py_list)

# print(np_arr)

# b) Exploring attributes of numpy array
print("Axes of the array:", np_arr.ndim)
print("Data type of the array:", np_arr.dtype)
print("Item size (no. of bytes for each element) in the array:", np_arr.itemsize)
print("Numpy array contents:", np_arr.data) # the buffer containing the actual elements of the array

print("Reshaped array:\n",np_arr.reshape(3,4)) # Changing dimensions of existing array
print("Flattened array",np_arr.flatten()) # Return a copy of the array collapsed into one dimension



Axes of the array: 2
Data type of the array: int64
Item size (no. of bytes for each element) in the array: 8
Numpy array contents: <memory at 0x1312c7e10>
Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array [ 1  2  3  4  5  6  7  8  9 10 11 12]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [165]:
temp_arr = np.arange(10,30,1)

# Slicing 1D arr
print("1D array slice:",temp_arr[0:10])

# Slicing 2D arr
def f(x, y):
    return 10 * x - y

b = np.fromfunction(f, (5, 4), dtype=int)
print("2D array:\n",b)
print("2D array slice",b[1:, 2])

# Array ops:
print('Index of largest element (in flattened array)', np.argmax(b))
print('Max el', np.max(b))
print('Index of smallest element (in flattened array)', np.argmin(b))
print('Min el', np.min(b))
print('Mean', np.mean(b))
# print('abs\n', np.abs(b))
# print('exp\n', np.exp(b))
# print('sqrt\n', np.sqrt(b))
print('square\n', np.square(b))
print('sum', np.sum(b))
print('std dev', np.std(b))

# a = [[1, 0], [0, 1]]
# b = [[4, 1], [2, 2]]
# print(np.dot(a, b))

# print("sign",np.sign(b))
print("mod", np.mod(b, 50))

print('-'*40)


1D array slice: [10 11 12 13 14 15 16 17 18 19]
2D array:
 [[ 0 -1 -2 -3]
 [10  9  8  7]
 [20 19 18 17]
 [30 29 28 27]
 [40 39 38 37]]
2D array slice [ 8 18 28 38]
Index of largest element (in flattened array) 16
Max el 40
Index of smallest element (in flattened array) 3
Min el -3
Mean 18.5
square
 [[   0    1    4    9]
 [ 100   81   64   49]
 [ 400  361  324  289]
 [ 900  841  784  729]
 [1600 1521 1444 1369]]
sum 370
std dev 14.186260959111108
mod [[ 0 49 48 47]
 [10  9  8  7]
 [20 19 18 17]
 [30 29 28 27]
 [40 39 38 37]]
----------------------------------------


In [177]:
np.ones((3,4), int)
np.zeros((3,4), int)
np.eye(5)
np.linspace(0, 10, 20)


arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]
